
export const getPackageDetailDimension = [
    {
        id: 1,
        name: 'Box 2 Flat',
        length: "34",
        width: "33",
        height: "6",
        weight: 1.5,
    },
    {
        id: 2,
        name: 'Box 3',
        length: "33",
        width: "32",
        height: "10",
        weight: 2,
    },
    {
        id: 3,
        name: 'Box 4',
        length: "33",
        width: "32",
        height: "18",
        weight: 5,
    },
    {
        id: 4,
        name: 'Box 5(Jumbo Small)',
        length: "34",
        width: "33",
        height: "35",
        weight: 10,
    },
    {
        id: 5,
        name: 'Box 6',
        length: "41",
        width: "35",
        height: "36",
        weight: 15,
    },
    {
        id: 6,
        name: 'Box 7',
          length: "48",
          width: "40",
          height: "38",
          weight: 20,
      },
      {
        id: 7,
        name: 'Box 8(Jumbo Large)',
          length: "55",
          width: "45",
          height: "41",
          weight: 25,
      },
      {
        id: 8,
        name: 'Velo Flyer',
          length: "47",
          width: "38",
          height: "1",
          weight: 25,
      },
      {
        id: 9,
        name: 'Envelope',
          length: "31",
          width: "23",
          height: "1",
          weight: 0.3,
      },
]
