import type { SeoPageConfig } from '@/types/seo';
import { h2 } from './utils';

export const seoPages: SeoPageConfig[] = [
  {
    slug: 'home',
    path: '/',
    titleTag: 'International Shipping from Dubai to Kenya | Velo',
    description:
      'Ship from Dubai to Kenya without the hassle. Arrange pickup, track in real time, and manage personal or commercial cargo from one place.',
    h1: 'Ship from Dubai to Kenya Without the Hassle',
    h2s: [
      h2('Air Freight Services'),
      h2('Sea Freight Solutions'),
      h2('Schedule Pickup Through the Velo App'),
      h2('Real-Time Shipment Tracking'),
      h2('Shipping Solutions for Businesses'),
      h2('Why Customers Choose Velo'),
      h2('Frequently Asked Questions'),
    ],
    primaryCta: { label: 'Request a Quote', href: '/contact' },
    internalLinks: [
      '/shipping-from-dubai-to-kenya',
      '/air-freight-dubai-to-kenya',
      '/sea-freight-dubai-to-kenya',
      '/package-pickup-dubai',
      '/business-shipping',
      '/pricing-calculator',
      '/track-shipment',
      '/download-app',
      '/contact',
    ],
    schemaTypes: ['Organization', 'WebSite', 'FAQPage', 'SoftwareApplication'],
    intent: 'commercial',
    template: 'custom',
    sitemapPriority: 1,
  },
  {
    slug: 'shipping-from-dubai-to-kenya',
    path: '/shipping-from-dubai-to-kenya',
    titleTag: 'Shipping from Dubai to Kenya | Velo Logistics',
    description:
      'Shipping from Dubai to Kenya with pickup, real-time tracking, and air or sea freight. International shipping from Dubai to Kenya for personal and commercial cargo.',
    h1: "Shipping from Dubai to Kenya Doesn't Have to Involve Three Different People",
    h2s: [
      h2('Air Freight Services'),
      h2('Sea Freight Options'),
      h2('Door-to-Door Delivery'),
      h2('Delivery Times'),
      h2('Real-Time Tracking'),
      h2('Pricing Calculator'),
      h2('Frequently Asked Questions'),
    ],
    primaryCta: { label: 'Request a Quote', href: '/contact' },
    internalLinks: [
      '/air-freight-dubai-to-kenya',
      '/sea-freight-dubai-to-kenya',
      '/package-pickup-dubai',
      '/pricing-calculator',
      '/track-shipment',
      '/contact',
    ],
    schemaTypes: ['FAQPage', 'Service'],
    intent: 'commercial',
    template: 'marketing',
    footerGroup: 'routes',
    footerLabel: 'Dubai to Kenya Shipping',
    sitemapPriority: 0.9,
  },
  {
    slug: 'cargo-services-dubai-to-nairobi',
    path: '/cargo-services-dubai-to-nairobi',
    titleTag: 'Cargo Services Dubai to Nairobi | Velo',
    description: 'Cargo services from Dubai to Nairobi. Air and sea cargo options with pickup and tracking.',
    h1: 'Cargo Services from Dubai to Nairobi',
    h2s: [
      h2('Air Cargo Options'),
      h2('Sea Cargo Solutions'),
      h2('Delivery Timelines'),
      h2('Pickup Services'),
      h2('Tracking Your Shipment'),
      h2('Frequently Asked Questions'),
    ],
    primaryCta: { label: 'Calculate Shipping Cost', href: '/pricing-calculator' },
    internalLinks: ['/shipping-from-dubai-to-kenya', '/air-freight-dubai-to-kenya', '/track-shipment'],
    schemaTypes: ['FAQPage', 'Service'],
    intent: 'commercial',
    template: 'marketing',
    footerGroup: 'routes',
    footerLabel: 'Dubai to Nairobi Cargo',
    sitemapPriority: 0.9,
  },
  {
    slug: 'door-to-door-shipping-kenya',
    path: '/door-to-door-shipping-kenya',
    titleTag: 'Door-to-Door Shipping Dubai to Kenya | Velo',
    description:
      'Door-to-door shipping Dubai to Kenya with pickup and delivery in one process. Package delivery Dubai to Kenya with tracking from collection to destination.',
    h1: "Shipping Is Easier When You Don't Have to Piece Everything Together",
    h2s: [
      h2('How Pickup Works'),
      h2('Delivery Process'),
      h2('Tracking Your Package'),
      h2('Areas We Deliver'),
      h2('Frequently Asked Questions'),
    ],
    primaryCta: { label: 'Request a Quote', href: '/contact' },
    internalLinks: ['/package-pickup-dubai', '/track-shipment', '/shipping-from-dubai-to-kenya'],
    schemaTypes: ['Service', 'FAQPage'],
    intent: 'commercial',
    template: 'marketing',
    footerGroup: 'services',
    footerLabel: 'Door-to-Door Shipping',
    sitemapPriority: 0.8,
  },
  {
    slug: 'air-freight-dubai-to-kenya',
    path: '/air-freight-dubai-to-kenya',
    titleTag: 'Air Freight Dubai to Kenya | Velo',
    description:
      'Air freight from Dubai to Kenya for urgent cargo. Express shipping Dubai to Kenya with pickup, real-time tracking, and delivery across Kenya.',
    h1: "When Time Matters, Waiting Isn't an Option",
    h2s: [
      h2('Transit Times'),
      h2('Suitable Cargo Types'),
      h2('Tracking'),
      h2('Pickup Options'),
      h2('Pricing Calculator'),
      h2('FAQs'),
    ],
    primaryCta: { label: 'Request an Air Freight Quote', href: '/contact' },
    internalLinks: [
      '/shipping-from-dubai-to-kenya',
      '/sea-freight-dubai-to-kenya',
      '/pricing-calculator',
      '/track-shipment',
    ],
    schemaTypes: ['Service', 'FAQPage'],
    intent: 'transactional',
    template: 'marketing',
    footerGroup: 'services',
    footerLabel: 'Air Freight',
    sitemapPriority: 0.8,
  },
  {
    slug: 'sea-freight-dubai-to-kenya',
    path: '/sea-freight-dubai-to-kenya',
    titleTag: 'Sea Freight Dubai to Kenya | Velo',
    description:
      'Sea freight from Dubai to Kenya for larger shipments and heavier cargo. Ocean freight Dubai to Kenya with pickup, tracking, and container shipping to Kenya.',
    h1: 'Not Every Shipment Needs to Get There Tomorrow',
    h2s: [
      h2('Container Options'),
      h2('Delivery Timelines'),
      h2('Commercial Cargo'),
      h2('Tracking'),
      h2('FAQs'),
    ],
    primaryCta: { label: 'Request a Sea Freight Quote', href: '/contact' },
    internalLinks: ['/shipping-from-dubai-to-kenya', '/business-shipping', '/track-shipment'],
    schemaTypes: ['FAQPage', 'Service'],
    intent: 'transactional',
    template: 'marketing',
    footerGroup: 'services',
    footerLabel: 'Sea Freight',
    sitemapPriority: 0.8,
  },
  {
    slug: 'package-pickup-dubai',
    path: '/package-pickup-dubai',
    titleTag: 'Package Pickup Dubai | Velo',
    description:
      'Package pickup Dubai from your home, office, or warehouse. Package collection service Dubai and shipping pickup UAE with tracking to Kenya.',
    h1: "Sending a Package Shouldn't Begin With a Drive Across the City",
    h2s: [
      h2('Schedule Pickup Through the App'),
      h2('Areas Covered'),
      h2('Pickup Process'),
      h2('Frequently Asked Questions'),
    ],
    primaryCta: { label: 'Schedule a Pickup', href: '/download-app' },
    internalLinks: ['/door-to-door-shipping-kenya', '/track-shipment', '/download-app'],
    schemaTypes: ['Service', 'FAQPage'],
    intent: 'transactional',
    template: 'marketing',
    footerGroup: 'services',
    footerLabel: 'Package Pickup',
    sitemapPriority: 0.8,
  },
  {
    slug: 'business-shipping',
    path: '/business-shipping',
    titleTag: 'Business Shipping Dubai to Kenya | Velo',
    description:
      'Business shipping Dubai to Kenya for commercial cargo and inventory. B2B shipping services UAE with pickup, tracking, and freight forwarding to Kenya.',
    h1: "Your Business Can't Afford to Run on Follow-Ups",
    h2s: [
      h2('Bulk Shipments'),
      h2('Reporting Dashboard'),
      h2('Shipment Visibility'),
      h2('Pickup Scheduling'),
      h2('Tracking'),
      h2('FAQs'),
    ],
    primaryCta: { label: 'Request a Business Quote', href: '/contact' },
    internalLinks: ['/sea-freight-dubai-to-kenya', '/pricing-calculator', '/contact'],
    schemaTypes: ['Service', 'FAQPage'],
    intent: 'commercial',
    template: 'marketing',
    footerGroup: 'company',
    footerLabel: 'Business Shipping',
    sitemapPriority: 0.8,
  },
  {
    slug: 'about',
    path: '/about',
    titleTag: 'Shipping Company in Dubai | Velo',
    description:
      'Velo is a shipping company in Dubai helping customers and businesses with cargo services Dubai to Kenya. International shipping company UAE with pickup, tracking, and delivery.',
    h1: 'Shipping Has Worked the Same Way for Years. We Think It Can Work Better.',
    h2s: [
      h2('Who We Are'),
      h2('Why Customers Choose Velo'),
      h2('Coverage Areas'),
      h2('Real-Time Tracking'),
      h2('Frequently Asked Questions'),
    ],
    primaryCta: { label: 'Request a Quote', href: '/contact' },
    internalLinks: ['/shipping-from-dubai-to-kenya', '/contact', '/download-app'],
    schemaTypes: ['Organization', 'LocalBusiness'],
    intent: 'local',
    template: 'marketing',
    footerGroup: 'company',
    footerLabel: 'About',
    sitemapPriority: 0.7,
  },
  {
    slug: 'track-shipment',
    path: '/track-shipment',
    titleTag: 'Track Shipment Dubai to Kenya | Velo',
    description:
      'Track shipment Dubai to Kenya in real time. Cargo tracking Dubai to Kenya and parcel tracking UAE to Kenya from pickup to delivery.',
    h1: "You Shouldn't Have to Call Someone Just to Know Where Your Shipment Is",
    h2s: [
      h2('Shipment Status'),
      h2('Delivery Timeline'),
      h2('Notifications'),
      h2('Need Help?'),
    ],
    primaryCta: { label: 'Track Your Shipment', href: '#track-form' },
    internalLinks: ['/contact', '/download-app'],
    schemaTypes: ['SoftwareApplication'],
    intent: 'transactional',
    template: 'tool',
    footerGroup: 'company',
    footerLabel: 'Track Shipment',
    sitemapPriority: 0.7,
  },
  {
    slug: 'pricing-calculator',
    path: '/pricing-calculator',
    titleTag: 'Shipping Cost Dubai to Kenya | Velo',
    description:
      'Shipping cost Dubai to Kenya calculator. Estimate freight charges Dubai to Kenya and parcel shipping rates UAE to Kenya based on weight, dimensions, and cargo type.',
    h1: 'The First Question Most People Ask Is About Cost',
    h2s: [
      h2('How Pricing Works'),
      h2('Weight-Based Charges'),
      h2('Commercial Cargo'),
      h2('Frequently Asked Questions'),
    ],
    primaryCta: { label: 'Calculate Shipping Costs', href: '#calculator' },
    internalLinks: ['/air-freight-dubai-to-kenya', '/sea-freight-dubai-to-kenya', '/business-shipping'],
    schemaTypes: ['FAQPage'],
    intent: 'transactional',
    template: 'tool',
    footerGroup: 'resources',
    footerLabel: 'Pricing Calculator',
    sitemapPriority: 0.8,
  },
  {
    slug: 'blog-shipping-cost-dubai-to-kenya',
    path: '/blog/shipping-cost-dubai-to-kenya',
    titleTag: 'How Much Does Shipping from Dubai to Kenya Cost? | Velo',
    description: 'Learn what affects shipping costs from Dubai to Kenya including air vs sea freight factors.',
    h1: 'How Much Does Shipping from Dubai to Kenya Cost?',
    h2s: [
      h2('Factors Affecting Cost'),
      h2('Air Freight vs Sea Freight'),
      h2('Pricing Examples'),
      h2('FAQs'),
    ],
    primaryCta: { label: 'Estimate Your Shipping Cost', href: '/pricing-calculator' },
    internalLinks: ['/pricing-calculator', '/air-freight-dubai-to-kenya', '/sea-freight-dubai-to-kenya'],
    schemaTypes: ['Article', 'FAQPage'],
    intent: 'informational',
    template: 'blog',
    footerGroup: 'resources',
    footerLabel: 'Shipping Cost Guide',
    sitemapPriority: 0.6,
  },
  {
    slug: 'blog-air-freight-vs-sea-freight-kenya',
    path: '/blog/air-freight-vs-sea-freight-kenya',
    titleTag: 'Air Freight vs Sea Freight to Kenya | Velo',
    description: 'Compare air freight and sea freight to Kenya to choose the right shipping method.',
    h1: 'Air Freight vs Sea Freight: Which Option Is Right for You?',
    h2s: [],
    primaryCta: { label: 'Request a Quote', href: '/contact' },
    internalLinks: ['/air-freight-dubai-to-kenya', '/sea-freight-dubai-to-kenya'],
    schemaTypes: ['Article'],
    intent: 'informational',
    template: 'blog',
    footerGroup: 'resources',
    footerLabel: 'Air vs Sea Freight',
    sitemapPriority: 0.6,
  },
  {
    slug: 'contact',
    path: '/contact',
    titleTag: 'Shipping Company in Dubai | Contact Velo',
    description:
      'Contact Velo, a shipping company in Dubai, for cargo services Dubai to Kenya, quotes, and support. International shipping company Dubai for personal and business shipments.',
    h1: 'Sometimes You Just Want an Answer',
    h2s: [],
    primaryCta: { label: 'Request a Quote', href: '/contact' },
    internalLinks: ['/shipping-from-dubai-to-kenya', '/download-app'],
    schemaTypes: ['Organization'],
    intent: 'transactional',
    template: 'custom',
    footerGroup: 'company',
    footerLabel: 'Contact',
    sitemapPriority: 0.7,
  },
  {
    slug: 'download-app',
    path: '/download-app',
    titleTag: 'Download the Velo App | iOS & Android',
    description: 'Download the Velo app for iOS and Android. Manage shipments from Dubai to Kenya on the go.',
    h1: 'Download the Velo App',
    h2s: [],
    primaryCta: { label: 'Download the App', href: '/download-app' },
    internalLinks: ['/track-shipment', '/package-pickup-dubai'],
    schemaTypes: ['SoftwareApplication'],
    intent: 'transactional',
    template: 'custom',
    footerGroup: 'company',
    footerLabel: 'Download App',
    sitemapPriority: 0.7,
  },
  {
    slug: 'account-delete-guide',
    path: '/account-delete-guide',
    titleTag: 'Account Delete Guide | Velo',
    description: 'How to delete your Velo account.',
    h1: 'How to Delete Your VELO Account',
    h2s: [],
    primaryCta: { label: 'Contact Support', href: '/contact' },
    internalLinks: [],
    schemaTypes: [],
    intent: 'utility',
    template: 'custom',
    noindex: true,
  },
];

export function getPageConfig(slug: string): SeoPageConfig {
  const page = seoPages.find((p) => p.slug === slug);
  if (!page) throw new Error(`Unknown SEO page slug: ${slug}`);
  return page;
}

export function getPageConfigByPath(path: string): SeoPageConfig | undefined {
  return seoPages.find((p) => p.path === path);
}

export function getAllPages(): SeoPageConfig[] {
  return seoPages;
}

export function getIndexablePages(): SeoPageConfig[] {
  return seoPages.filter((p) => !p.noindex);
}

export function getFooterLinks(group: SeoPageConfig['footerGroup']) {
  return seoPages.filter((p) => p.footerGroup === group && p.footerLabel && !p.noindex);
}
