-- AlterTable
ALTER TABLE `Agent` MODIFY `role` ENUM('AGENT', 'USER', 'SUPERADMIN', 'SUB_AGENT') NOT NULL;

-- AlterTable
ALTER TABLE `SuperAdmin` MODIFY `role` ENUM('AGENT', 'USER', 'SUPERADMIN', 'SUB_AGENT') NOT NULL;

-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('AGENT', 'USER', 'SUPERADMIN', 'SUB_AGENT') NOT NULL;
